apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: task-api
  template:
    metadata:
      labels:
        app: task-api
    spec: 
      containers:
        - name: task
          image: vaibhavrajnathchauhan/kub-task-demo:8
          env:
            - name: AUTH_ADDRESS
              # value: "10.108.4.235"   # -> service ip address 
              # or
              value: "auth-service.default"  # -> service name + namespace
            - name: TASKS_FOLDER
              value: tasks